### ISSUE TITLE
Errors out for coverage on index file that only exports and import

### ISSUE THREAD

**Issue by keithhalterman** [CanopyTax/node-jspm-jasmine#35]
This is a catastrophic failure, does not recover. 

```
Failed to parse file: /Users/keith/dev/invite-collab-modal/node_modules/node-jspm-jasmine/transpiled-modules/src/index.js

************ node-jspm-jasmine tests completed in 4539 milliseconds ************
Error: Line 1: Unexpected token
    at constructError (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2500:13)
    at tolerateUnexpectedToken (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2509:21)
    at parseStatementListItem (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3968:21)
    at parseFunctionSourceElements (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:5074:16)
    at parsePrimaryExpression (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3273:24)
    at inheritCoverGrammar (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3414:20)
    at inheritCoverGrammar (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2681:18)
    at parsePostfixExpression (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3490:16)
    at parseUnaryExpression (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3550:20)
    at inheritCoverGrammar (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2681:18)
    at parseBinaryExpression (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:3639:16)
    at inheritCoverGrammar (/Users/keith/dev/invite-collab-modal/node_modules/esprima/esprima.js:2681:18)
```

This is the file that is erring when it's parsed: index.js
`export ClientCollaboratorsModal from './collab-modal.component.js';`

**Comment by keithhalterman** [comment]
our bad, wrote a syntax error
